import { useEffect, useState, type ReactNode } from "react";
import { ArrowLeft, Bell, Check, ChevronRight, Database, FileText, HelpCircle, Info, LogOut, Moon, RotateCcw, ShieldCheck, Sun, UserRound } from "lucide-react";
import { getSettings, resetSettings, subscribeToSettings, updateSettings, type AppLanguage, type Appearance, type CommentPrivacy, type MessagePrivacy, type StoryPrivacy, type YunikoSettings } from "./settings.service";

type Section = "main" | "account" | "privacy" | "notifications" | "data" | "moderation" | "about" | "blocked" | "reports" | "terms" | "policy" | "guidelines" | "support" | "profile-editor" | "credentials";

export function SettingsPage({ onBack, onOpenSecurity }: { onBack: () => void; onOpenSecurity: () => void }) {
  const [settings, setSettings] = useState<YunikoSettings>(() => getSettings());
  const [section, setSection] = useState<Section>("main");
  useEffect(() => subscribeToSettings(() => setSettings(getSettings())), []);
  const change = (patch: Partial<YunikoSettings>) => setSettings(updateSettings(patch));
  const title: Record<Section, string> = { main: "Settings", account: "Account", privacy: "Privacy", notifications: "Notifications", data: "Your data", moderation: "Safety & moderation", about: "Information", blocked: "Blocked accounts", reports: "My reports", terms: "Terms of use", policy: "Privacy policy", guidelines: "Community guidelines", support: "Help & support", "profile-editor": "Edit profile", credentials: "Email & password" };
  if (section !== "main") return <SubPage title={title[section]} onBack={() => setSection("main")}>
    {section === "account" && <><InfoBox>Manage the identity and profile information shown on Yuniko.</InfoBox><ActionRow title="Edit profile" description="Change your profile photo, username, bio and links." onClick={() => setSection("profile-editor")} /><ActionRow title="Email & password" description="Account credentials are local prototype controls until real authentication is connected." onClick={() => setSection("credentials")} /></>}
    {section === "profile-editor" && <InfoBox>Profile editing is currently handled by the Profile surface. This prototype keeps this entry point ready for the account editor without changing server data.</InfoBox>}
    {section === "credentials" && <InfoBox>Email and password changes require the future authentication service. No credential is stored or exposed by this frontend-only prototype.</InfoBox>}
    {section === "privacy" && <><SettingRow title="Private account" description="Only approved followers can follow this account." value={settings.privateAccount} onChange={v => change({ privateAccount: v })} /><SettingRow title="Activity status" description="Allow people to see when you are active." value={settings.showActivityStatus} onChange={v => change({ showActivityStatus: v })} /><SelectRow title="Who can message you" value={settings.messagePrivacy} options={["everyone", "followers", "nobody"]} onChange={v => change({ messagePrivacy: v as MessagePrivacy })} /><SelectRow title="Who can view your stories" value={settings.storyPrivacy} options={["everyone", "followers", "close_friends"]} onChange={v => change({ storyPrivacy: v as StoryPrivacy })} /><SelectRow title="Who can comment" value={settings.commentPrivacy} options={["everyone", "followers", "nobody"]} onChange={v => change({ commentPrivacy: v as CommentPrivacy })} /><ActionRow title="Blocked accounts" description="Manage accounts blocked on this device." onClick={() => setSection("blocked")} /></>}
    {section === "notifications" && <><SettingRow title="Push notifications" description="Receive notification alerts on this device." value={settings.pushNotifications} onChange={v => change({ pushNotifications: v })} /><SettingRow title="Messages" description="Alerts for new private messages." value={settings.messageNotifications} onChange={v => change({ messageNotifications: v })} /><SettingRow title="Likes" description="Alerts when someone likes your content." value={settings.likeNotifications} onChange={v => change({ likeNotifications: v })} /><SettingRow title="Comments" description="Alerts for comments and replies." value={settings.commentNotifications} onChange={v => change({ commentNotifications: v })} /><SettingRow title="Followers" description="New followers and follow requests." value={settings.followerNotifications} onChange={v => change({ followerNotifications: v })} /><SettingRow title="Stories" description="Story-related notifications." value={settings.storyNotifications} onChange={v => change({ storyNotifications: v })} /><SettingRow title="Email notifications" description="Allow non-essential notification emails." value={settings.emailNotifications} onChange={v => change({ emailNotifications: v })} /></>}
    {section === "data" && <><InfoBox>Yuniko is currently frontend-only. These controls manage local prototype state, not server data.</InfoBox><ActionRow title="Local storage" description="Preferences, drafts and demo state may be stored locally on this device." onClick={() => setSection("data")} /><button type="button" className="settings-action danger" onClick={() => { if (window.confirm("Reset all local Yuniko preferences?")) setSettings(resetSettings()); }}><Database size={17}/><span><strong>Reset local preferences</strong><small>Restore settings to their defaults.</small></span></button></>}
    {section === "moderation" && <><ActionRow title="Blocked accounts" description="Open blocked-user management." onClick={() => setSection("blocked")} /><ActionRow title="My reports" description="Review reports submitted from this device." onClick={() => setSection("reports")} /><InfoBox>Reporting and blocking use the local frontend moderation queue until the server moderation system is connected.</InfoBox></>}
    {section === "blocked" && <InfoBox>Blocked-account management is backed by the moderation service. Existing moderation controls on profiles and posts remain the place to block or unblock a user in this frontend prototype.</InfoBox>}
    {section === "reports" && <InfoBox>Your submitted reports are stored in the local moderation queue during this frontend-only stage. Server-side review will be connected later.</InfoBox>}
    {section === "about" && <><ActionRow title="Terms of use" description="Terms of use for Yuniko." onClick={() => setSection("terms")} /><ActionRow title="Privacy policy" description="How Yuniko will handle account and content data." onClick={() => setSection("policy")} /><ActionRow title="Community guidelines" description="Rules for respectful and safe participation." onClick={() => setSection("guidelines")} /><ActionRow title="Help & support" description="Help and support information." onClick={() => setSection("support")} /><div className="settings-version"><Info size={16}/>Yuniko frontend prototype</div></>}
    {section === "terms" && <InfoBox>Yuniko terms will define acceptable use, user responsibilities, content ownership and service rules before public launch.</InfoBox>}
    {section === "policy" && <InfoBox>Yuniko's privacy policy will document account, content, device and analytics data handling before public launch.</InfoBox>}
    {section === "guidelines" && <InfoBox>Be respectful. Do not use Yuniko for harassment, threats, scams, spam or prohibited content. Reports and blocks are available throughout the app.</InfoBox>}
    {section === "support" && <InfoBox>Help & support is currently a frontend information surface. A real support contact and help center will be connected when the backend and production identity system are added.</InfoBox>}
  </SubPage>;
  return <main className="settings-shell"><header className="settings-header"><button type="button" aria-label="Back" onClick={onBack}><ArrowLeft size={21}/></button><strong>Settings</strong><span/></header><section className="settings-scroll">
    <MenuRow icon={<UserRound size={18}/>} title="Account" description="Profile and account information" onClick={() => setSection("account")}/>
    <MenuRow icon={<ShieldCheck size={18}/>} title="Privacy" description="Control visibility, messages and comments" onClick={() => setSection("privacy")}/>
    <MenuRow icon={<Bell size={18}/>} title="Notifications" description="Choose what Yuniko can notify you about" onClick={() => setSection("notifications")}/>
    <section className="settings-card"><h2><Moon size={18}/>Appearance</h2><div className="settings-choice-grid">{(["system","light","dark"] as Appearance[]).map(v => <button type="button" key={v} className={settings.appearance === v ? "selected" : ""} onClick={() => change({ appearance: v })}>{v === "system" ? "System" : v === "light" ? <><Sun size={16}/>Light</> : <><Moon size={16}/>Dark</>}{settings.appearance === v && <Check size={15}/>}</button>)}</div></section>
    <section className="settings-card"><h2>Language</h2><select value={settings.language} onChange={e => change({ language: e.target.value as AppLanguage })} aria-label="Language"><option value="system">Phone default</option><option value="fr">Français</option><option value="en">English</option><option value="mg">Malagasy</option></select></section>
    <MenuRow icon={<Database size={18}/>} title="Your data" description="Local data and prototype storage" onClick={() => setSection("data")}/><MenuRow icon={<ShieldCheck size={18}/>} title="Security" description="Sessions, login activity and 2FA prototype" onClick={onOpenSecurity}/><MenuRow icon={<HelpCircle size={18}/>} title="Safety & moderation" description="Blocked accounts and your reports" onClick={() => setSection("moderation")}/><MenuRow icon={<FileText size={18}/>} title="Information" description="Terms, privacy, guidelines and support" onClick={() => setSection("about")}/>
    <section className="settings-card settings-account-actions"><button type="button" className="settings-action" onClick={() => window.dispatchEvent(new CustomEvent("yuniko:logout-requested"))}><LogOut size={17}/><span><strong>Log out</strong><small>Frontend prototype action</small></span></button><button type="button" className="settings-action danger" onClick={() => { if (window.confirm("Reset local Yuniko settings?")) setSettings(resetSettings()); }}><RotateCcw size={17}/><span><strong>Reset settings</strong><small>Restore default preferences on this device</small></span></button></section>
  </section></main>;
}
function SubPage({ title, onBack, children }: { title: string; onBack: () => void; children: ReactNode }) { return <main className="settings-shell"><header className="settings-header"><button type="button" aria-label="Back" onClick={onBack}><ArrowLeft size={21}/></button><strong>{title}</strong><span/></header><section className="settings-scroll">{children}</section></main>; }
function MenuRow({ icon, title, description, onClick }: { icon: ReactNode; title: string; description: string; onClick: () => void }) { return <section className="settings-card settings-menu"><button type="button" className="settings-action" onClick={onClick}>{icon}<span><strong>{title}</strong><small>{description}</small></span><ChevronRight size={17}/></button></section>; }
function ActionRow({ title, description, onClick }: { title: string; description: string; onClick: () => void }) { return <section className="settings-card"><button type="button" className="settings-action" onClick={onClick}><span><strong>{title}</strong><small>{description}</small></span><ChevronRight size={17}/></button></section>; }
function InfoBox({ children }: { children: ReactNode }) { return <div className="settings-info">{children}</div>; }
function SelectRow({ title, value, options, onChange }: { title: string; value: string; options: string[]; onChange: (v: string) => void }) { return <div className="settings-row"><div><strong>{title}</strong></div><select value={value} onChange={e => onChange(e.target.value)}>{options.map(o => <option key={o} value={o}>{o.replaceAll("_", " ").replace(/\b\w/g, c => c.toUpperCase())}</option>)}</select></div>; }
function SettingRow({ title, description, value, onChange }: { title: string; description: string; value: boolean; onChange: (value: boolean) => void }) { return <div className="settings-row"><div><strong>{title}</strong><small>{description}</small></div><button type="button" className={`settings-toggle ${value ? "on" : ""}`} aria-pressed={value} onClick={() => onChange(!value)}><span/></button></div>; }
