import { requireSupabase, requireYunikoDb } from "../../lib/supabase";

export type AppLanguage = "system"|"fr"|"en"|"mg"; export type Appearance="system"|"light"|"dark"; export type MessagePrivacy="everyone"|"followers"|"nobody"; export type StoryPrivacy="everyone"|"followers"|"close_friends"; export type CommentPrivacy="everyone"|"followers"|"nobody";
export type YunikoSettings={language:AppLanguage;appearance:Appearance;pushNotifications:boolean;messageNotifications:boolean;emailNotifications:boolean;likeNotifications:boolean;commentNotifications:boolean;followerNotifications:boolean;storyNotifications:boolean;privateAccount:boolean;showActivityStatus:boolean;messagePrivacy:MessagePrivacy;storyPrivacy:StoryPrivacy;commentPrivacy:CommentPrivacy};
export const DEFAULT_SETTINGS:YunikoSettings={language:"system",appearance:"system",pushNotifications:true,messageNotifications:true,emailNotifications:false,likeNotifications:true,commentNotifications:true,followerNotifications:true,storyNotifications:true,privateAccount:false,showActivityStatus:true,messagePrivacy:"everyone",storyPrivacy:"everyone",commentPrivacy:"everyone"};
export async function getSettings():Promise<YunikoSettings>{const {data:{user},error}=await requireSupabase().auth.getUser();if(error)throw error;if(!user)throw new Error("Authentication required.");const {data,error:dbError}=await requireYunikoDb().from("user_settings").select("settings").eq("user_id",user.id).maybeSingle();if(dbError)throw dbError;return {...DEFAULT_SETTINGS,...((data?.settings as Partial<YunikoSettings>)??{})};}
export async function updateSettings(patch:Partial<YunikoSettings>):Promise<YunikoSettings>{const current=await getSettings();const next={...current,...patch};const {data:{user},error}=await requireSupabase().auth.getUser();if(error)throw error;if(!user)throw new Error("Authentication required.");const {error:dbError}=await requireYunikoDb().from("user_settings").upsert({user_id:user.id,settings:next,updated_at:new Date().toISOString()},{onConflict:"user_id"});if(dbError)throw dbError;return next;}
export async function resetSettings():Promise<YunikoSettings>{return updateSettings(DEFAULT_SETTINGS);}
export function subscribeToSettings(listener:()=>void):()=>void{return ()=>listener;}
