import { requireSupabase } from "../../lib/supabase";

export type SecurityState = { userId: string; twoFactorEnabled: boolean; recoveryCodes: string[] };
export type Session = { id:string; userId:string; deviceLabel:string; createdAt:string; lastSeenAt:string; current:boolean; ip:string|null; aal:string };
export type LoginEvent = { id:string; userId:string; createdAt:string; deviceLabel:string; countryCode:string; success:boolean };

export async function getSecurityState(): Promise<SecurityState> {
 const client=requireSupabase(); const {data:{user},error}=await client.auth.getUser(); if(error) throw error; if(!user) throw new Error("Authentication required.");
 const {data,error:factorError}=await client.auth.mfa.listFactors(); if(factorError) throw factorError;
 return {userId:user.id,twoFactorEnabled:(data?.all??[]).some(f=>f.status==="verified"),recoveryCodes:[]};
}
export async function beginTwoFactorEnrollment(){const {data,error}=await requireSupabase().auth.mfa.enroll({factorType:"totp",friendlyName:"Yuniko Authenticator"});if(error) throw error;return {factorId:data.id,qrCode:data.totp?.qr_code??"",secret:data.totp?.secret??""};}
export async function verifyTwoFactor(factorId:string,code:string){const client=requireSupabase();const {data:challenge,error:challengeError}=await client.auth.mfa.challenge({factorId});if(challengeError) throw challengeError;const {error}=await client.auth.mfa.verify({factorId,challengeId:challenge.id,code:code.trim()});if(error) throw error;}
export async function disableTwoFactor(){const client=requireSupabase();const {data,error}=await client.auth.mfa.listFactors();if(error) throw error;for(const factor of (data?.totp??[]).filter(f=>f.status==="verified")){const {error:unenrollError}=await client.auth.mfa.unenroll({factorId:factor.id});if(unenrollError) throw unenrollError;}}
export async function getSessions():Promise<Session[]>{const client=requireSupabase();const {data:{session},error}=await client.auth.getSession();if(error) throw error;if(!session) throw new Error("Authentication required.");const url=String(import.meta.env.VITE_SUPABASE_URL)+"/functions/v1/security-sessions";const response=await fetch(url,{headers:{Authorization:"Bearer "+session.access_token,apikey:String(import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY)}});const payload=await response.json();if(!response.ok) throw new Error(payload.error??"Unable to load sessions.");const payloadPart=session.access_token.split(".")[1];
 let currentSessionId="";
 try{currentSessionId=JSON.parse(atob(payloadPart.replace(/-/g,"+").replace(/_/g,"/"))).session_id??"";}catch{}
 return (payload.sessions??[]).map((s:{id:string;createdAt:string;lastSeenAt:string;userAgent:string;ip:string|null;aal:string})=>({id:s.id,userId:session.user.id,deviceLabel:s.userAgent,createdAt:s.createdAt,lastSeenAt:s.lastSeenAt,current:s.id===currentSessionId,ip:s.ip,aal:s.aal}));}
export async function revokeOtherSessions(){const client=requireSupabase();const {data:{session},error}=await client.auth.getSession();if(error) throw error;if(!session) throw new Error("Authentication required.");const response=await fetch(String(import.meta.env.VITE_SUPABASE_URL)+"/functions/v1/security-sessions",{method:"POST",headers:{Authorization:"Bearer "+session.access_token,apikey:String(import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY),"Content-Type":"application/json"},body:JSON.stringify({action:"revoke_others"})});if(!response.ok){const p=await response.json().catch(()=>({}));throw new Error(p.error??"Unable to revoke other sessions.");}}
export async function getLoginEvents():Promise<LoginEvent[]>{const client=requireSupabase();const {data:{user},error}=await client.auth.getUser();if(error) throw error;if(!user) throw new Error("Authentication required.");const {data,error:dbError}=await client.schema("yunikov_v1").from("login_events").select("id,user_id,created_at,device_label,country_code,success").eq("user_id",user.id).order("created_at",{ascending:false}).limit(20);if(dbError) throw dbError;return (data??[]).map(r=>({id:r.id,userId:r.user_id,createdAt:r.created_at,deviceLabel:r.device_label,countryCode:r.country_code??"",success:r.success}));}
export async function recordLoginEvent(success:boolean,deviceLabel="This device",countryCode="MG"){const client=requireSupabase();const {data:{user},error}=await client.auth.getUser();if(error) throw error;if(!user) return;const {error:dbError}=await client.schema("yunikov_v1").from("login_events").insert({user_id:user.id,success,device_label:deviceLabel,country_code:countryCode.toUpperCase()});if(dbError) throw dbError;}
