alter table public.posts
  add column if not exists deleted_at timestamptz;

create index if not exists posts_deleted_at_idx
  on public.posts (deleted_at)
  where deleted_at is not null;

create table if not exists public.post_edits (
  id bigint generated by default as identity primary key,
  post_id integer not null references public.posts(id) on delete cascade,
  editor_id integer not null references public.users(id) on delete cascade,
  previous_caption text not null,
  new_caption text not null,
  edited_at timestamptz not null default now()
);

create index if not exists post_edits_post_id_edited_at_idx
  on public.post_edits (post_id, edited_at desc);

alter table public.post_edits enable row level security;
